apiVersion: v1
kind: Service
metadata:
  name: vulnops-backend
  namespace: vulnops
spec:
  type: ClusterIP  # internal only — only the frontend can reach this
  selector:
    app: vulnops-backend
  ports:
    - port: 5000
      targetPort: 5000
