apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: vulnops
spec:
  accessModes:
    - ReadWriteOnce       # EBS volumes attach to one node at a time
  storageClassName: ebs-csi-gp2   # CSI-backed EBS storage class
  resources:
    requests:
      storage: 5Gi
