apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi-gp2
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp2
